 function validateDateRange(form){const start=form.elements.startDate;const end=form.elements.endDate;if(!start||!end)return;end.setCustomValidity(start.value&&end.value&&end.value<start.value?'End date cannot be before start date.':'')}
 document.addEventListener('input',event=>{if(event.target.form?.id==='create-form'||event.target.form?.id==='edit-form')validateDateRange(event.target.form)})
const baseRenderDetail = renderDetail;
renderDetail = (tab) => {
	baseRenderDetail(tab);
	const tournament = state.selected;
	if (tournament && canManageTournament() && tournament.status === 'REGISTRATION' && (tournament.format === 'ELIMINATION' || tournament.format === 'GROUPS')) {
		const action = document.createElement('button');
		action.className = 'button secondary';
		action.textContent = tournament.format === 'GROUPS' ? 'Generate group matches' : 'Generate bracket';
		action.onclick = async () => { try { await request(`/tournaments/${tournament.id}/generate-bracket`, {method:'POST'}); toast(tournament.format === 'GROUPS' ? 'Group matches generated' : 'Bracket generated'); renderDetail('bracket'); } catch (error) { toast(error.message); } };
		document.querySelector('.detail-head').append(action);
		const edit = document.createElement('button');
		edit.className = 'button secondary';
		edit.textContent = 'Edit details';
		edit.onclick = () => renderEditForm();
		document.querySelector('.detail-head').append(edit);
	}
};
function renderEditForm() {
	const tournament = state.selected;
	$('#app-content').innerHTML = `<button class="back" id="cancel-edit">&lt; Back to tournament</button><div class="form-panel"><h2>Edit tournament</h2><form id="edit-form" class="form-grid"><label>Name<input name="name" required maxlength="150" value="${esc(tournament.name)}"></label><label>Start date<input name="startDate" type="date" required value="${tournament.startDate}"></label><label>End date<input name="endDate" type="date" required value="${tournament.endDate}"></label><label class="full">Description<textarea name="description" maxlength="2000">${esc(tournament.description || '')}</textarea></label><div class="form-actions full"><button type="button" class="button secondary" id="cancel-edit-form">Cancel</button><button class="button primary">Save changes</button></div></form></div>`;
	$('#cancel-edit').onclick = () => renderDetail('overview');
	$('#cancel-edit-form').onclick = () => renderDetail('overview');
	$('#edit-form').onsubmit = async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.target).entries()); try { await request(`/tournaments/${tournament.id}`, {method:'PUT', body:JSON.stringify(payload)}); toast('Tournament updated'); loadDetail(tournament.id); } catch (error) { toast(error.message); } };
}
const API = (window.__API_URL__ || 'http://localhost:8080/api').replace(/\/$/, '');
const state = { credentials: null, username: null, role: null, tournaments: [], selected: null, notifications: [], notificationPollTimer: null };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const date = (value) => value ? new Date(value + (value.length === 10 ? 'T00:00:00' : '')).toLocaleDateString(undefined, {month:'short', day:'numeric', year:'numeric'}) : '-';
function toast(message){ const node=$('#toast'); node.textContent=message; node.classList.add('show'); setTimeout(()=>node.classList.remove('show'),3000); }
function friendlyError(status, body){const defaults={400:'Please check the entered values.',401:'Please sign in again.',403:'You do not have permission to perform this action.',404:'Resource not found.',409:'Operation conflicts with existing data.',500:'Something went wrong on the server.'};return status===400||status===409?body?.message||defaults[status]:(defaults[status]||`Request failed (${status})`)}
async function request(path, options={}) { const headers = {'Content-Type':'application/json', ...(options.headers||{})}; if(state.credentials) headers.Authorization=`Basic ${state.credentials}`; let response; try{response=await fetch(`${API}${path}`, {...options, headers})}catch{throw new Error('Unable to reach the server. Please try again.')} let body=null; try{body=response.status===204?null:await response.json()}catch{} if(response.status===401){stopNotificationPolling();state.credentials=null;state.username=null;state.role=null;showAuth();} if(!response.ok)throw new Error(friendlyError(response.status,body)); return body; }
function showAuth(mode='login'){ $('#auth-view').classList.remove('hidden'); $('#app-view').classList.add('hidden'); document.querySelectorAll('[data-auth]').forEach(tab=>tab.classList.toggle('active',tab.dataset.auth===mode)); const register=mode==='register'; $('#auth-title').textContent=register?'Create your account':'Welcome back'; $('#auth-subtitle').textContent=register?'Set up access to the tournament workspace.':'Sign in to manage your tournaments.'; $('#email-field').classList.toggle('hidden',!register); $('#email').required=register; $('#organizer-field').classList.toggle('hidden',!register); $('#auth-submit').textContent=register?'Create account':'Sign in'; $('#auth-error').textContent=''; $('#auth-form').dataset.mode=mode; }
async function authSubmit(event){event.preventDefault(); const register=$('#auth-form').dataset.mode==='register'; const payload={username:$('#username').value.trim(),password:$('#password').value}; if(register){payload.email=$('#email').value.trim();payload.organizer=$('#organizer').checked} $('#auth-submit').disabled=true; $('#auth-error').textContent=''; try{const response=await request(`/auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify(payload)}); state.credentials=btoa(`${payload.username}:${payload.password}`); state.username=response.username; state.role=response.role;showApp();toast(register?'Account created':'Signed in')}catch(error){$('#auth-error').textContent=error.message}finally{$('#auth-submit').disabled=false}}
function showApp(){ $('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-name').textContent=state.username;$('#user-role').textContent=state.role;$('#user-initial').textContent=state.username?.[0]?.toUpperCase()||'U';loadDashboard();loadNotifications();startNotificationPolling(); }
function statusClass(status){return status==='COMPLETED'?'complete':status==='IN_PROGRESS'?'progress':''}
function renderDashboard(){ const list=state.tournaments; const active=list.filter(item=>item.status==='IN_PROGRESS').length; $('#app-content').innerHTML=`<div class="stats"><div class="stat"><span class="eyebrow">Total tournaments</span><span class="number">${list.length}</span></div><div class="stat"><span class="eyebrow">In progress</span><span class="number">${active}</span></div><div class="stat"><span class="eyebrow">Your role</span><span class="number" style="font-size:22px">${esc(state.role)}</span></div></div><div class="section-head"><h2>All tournaments</h2><span class="muted">${list.length} records</span></div><div class="tournament-list">${list.length?list.map(item=>`<article class="tournament-card"><div class="card-top"><span class="badge ${statusClass(item.status)}">${esc(item.status.replace('_',' '))}</span><span class="muted">${esc(item.format)}</span></div><h3>${esc(item.name)}</h3><p>${esc(item.description||'No description provided.')}</p><div class="card-meta"><span>${date(item.startDate)} - ${date(item.endDate)}</span><span>${item.participantCount} entrants</span></div><button class="button secondary" style="margin-top:16px;width:100%" data-detail="${item.id}">Open tournament</button></article>`).join(''):'<div class="empty">No tournaments found.</div>'}</div>`; document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>loadDetail(button.dataset.detail)); }
async function loadDashboard(){ $('#page-title').textContent='Tournaments';$('#create-toggle').classList.toggle('hidden',state.role==='PARTICIPANT');$('#app-content').innerHTML='<div class="loading">Loading tournaments...</div>'; try{state.tournaments=await request('/tournaments');renderDashboard()}catch(error){$('#app-content').innerHTML=`<div class="error-box">${esc(error.message)}</div>`}}
function renderCreate(){ $('#page-title').textContent='New tournament';$('#create-toggle').classList.add('hidden');$('#app-content').innerHTML=`<button class="back" id="cancel-create">&lt; Back to tournaments</button><div class="form-panel"><h2>Create tournament</h2><p class="muted">Define the event before opening registration.</p><form id="create-form" class="form-grid"><label>Name<input name="name" required maxlength="150"></label><label>Format<select name="format"><option value="ELIMINATION">Elimination</option><option value="GROUPS">Groups</option></select></label><label>Start date<input name="startDate" type="date" required></label><label>End date<input name="endDate" type="date" required></label><label class="full">Description<textarea name="description" maxlength="2000"></textarea></label><div class="form-actions full"><button type="button" class="button secondary" id="cancel-form">Cancel</button><button class="button primary">Create tournament</button></div></form></div>`;$('#cancel-create').onclick=loadDashboard;$('#cancel-form').onclick=loadDashboard;$('#create-form').onsubmit=createTournament}
async function createTournament(event){event.preventDefault();const form=new FormData(event.target);const payload=Object.fromEntries(form.entries());try{await request('/tournaments',{method:'POST',body:JSON.stringify(payload)});toast('Tournament created');loadDashboard()}catch(error){toast(error.message)}}
async function loadDetail(id){$('#page-title').textContent='Tournament details';$('#create-toggle').classList.add('hidden');$('#app-content').innerHTML='<div class="loading">Loading tournament...</div>';try{state.selected=await request(`/tournaments/${id}`);renderDetail('overview')}catch(error){$('#app-content').innerHTML=`<div class="error-box">${esc(error.message)}</div>`}}
function renderDetail(tab){const t=state.selected;$('#app-content').innerHTML=`<button class="back" id="back-dashboard">&lt; All tournaments</button><div class="detail-head"><div><span class="badge ${statusClass(t.status)}">${esc(t.status.replace('_',' '))}</span><h2>${esc(t.name)}</h2><p>${esc(t.description||'No description provided.')} ${date(t.startDate)} - ${date(t.endDate)}</p></div>${canManageTournament()&&t.status==='REGISTRATION'?'<button class="button primary" id="add-participant">+ Add participant</button>':''}</div><div class="tabs"><button class="detail-tab active" data-tab="overview">Overview</button><button class="detail-tab" data-tab="bracket">Bracket</button><button class="detail-tab" data-tab="rankings">Rankings</button></div><div id="detail-body"><div class="loading">Loading data...</div></div>`;$('#back-dashboard').onclick=loadDashboard;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderDetailBody(button.dataset.tab)});if($('#add-participant'))$('#add-participant').onclick=addParticipant;renderDetailBody(tab)}
async function addParticipant(){const name=prompt('Participant name');if(!name?.trim())return;const username=prompt('Link to an existing account username (optional, so this participant receives real match/result notifications). Leave blank to skip.');try{const payload={name:name.trim()};if(username?.trim())payload.username=username.trim();await request(`/tournaments/${state.selected.id}/participants`,{method:'POST',body:JSON.stringify(payload)});toast('Participant added');renderDetailBody('overview')}catch(error){toast(error.message)}}
async function loadNotifications(){try{const data=await request('/notifications?unread=true');$('#notification-count').textContent=data.length||''}catch{}}
// Lightweight near-real-time notifications: periodic polling of the existing unread endpoint.
// No WebSocket/SSE - the app has no persistent-connection infrastructure today, and a REST poll every
// 30s is simple, requires no new dependency, and degrades gracefully (a failed poll just tries again
// next tick; loadNotifications() already swallows errors so the UI never breaks).
const NOTIFICATION_POLL_INTERVAL_MS = 30000;
function startNotificationPolling(){
	stopNotificationPolling(); // idempotent: never allow more than one timer running at once
	state.notificationPollTimer = setInterval(() => { if (!document.hidden) loadNotifications() }, NOTIFICATION_POLL_INTERVAL_MS);
}
function stopNotificationPolling(){
	if (state.notificationPollTimer) { clearInterval(state.notificationPollTimer); state.notificationPollTimer = null }
}
document.addEventListener('visibilitychange', () => { if (!document.hidden && state.credentials) loadNotifications() });
function notificationTypeLabel(type){return type==='MATCH_SCHEDULED'?'Upcoming match':type==='TOURNAMENT_COMPLETED'?'Final results':type==='MATCH_RESULT'?'Match result':type.replaceAll('_',' ')}
function notificationDetails(item){const type=notificationTypeLabel(item.type);const isMatch=Boolean(item.matchId);return `<div class="drawer-backdrop" data-close-drawer></div><aside class="match-drawer" role="dialog" aria-modal="true" aria-labelledby="notif-drawer-title"><button class="drawer-close" type="button" data-close-drawer aria-label="Close notification details">&times;</button><p class="eyebrow">${esc(type)}</p><h2 id="notif-drawer-title">${esc(item.tournamentName||'Tournament')}</h2><div class="drawer-status"><span class="match-state ${item.read?'completed':'ready'}">${item.read?'Read':'Unread'}</span>${isMatch&&item.matchStatus?`<span class="match-state ${bracketStatusClass(item.matchStatus)}">${esc(bracketStatusLabel(item.matchStatus))}</span>`:''}</div><p style="line-height:1.6">${esc(item.message)}</p><dl class="match-facts">${isMatch?`<div><dt>Round / Match</dt><dd>${item.round} / ${item.matchNumber}</dd></div>${item.opponent?`<div><dt>Opponent</dt><dd>${esc(item.opponent)}</dd></div>`:''}<div><dt>Scheduled</dt><dd>${item.scheduledTime?esc(new Date(item.scheduledTime).toLocaleString()):'To be announced'}</dd></div>`:''}<div><dt>Received</dt><dd>${esc(date(item.createdAt))}</dd></div></dl>${!item.read?'<button class="button primary wide" id="notif-mark-read" type="button">Mark as read</button>':''}</aside>`}
function openNotificationDrawer(item){closeMatchDrawer();document.body.insertAdjacentHTML('beforeend',notificationDetails(item));document.querySelectorAll('[data-close-drawer]').forEach(node=>node.onclick=closeMatchDrawer);const markBtn=$('#notif-mark-read');if(markBtn)markBtn.onclick=async()=>{try{await request(`/notifications/${item.id}/read`,{method:'PUT'});closeMatchDrawer();toast('Marked as read');renderNotifications();loadNotifications()}catch(error){toast(error.message)}}}
async function renderNotifications(){ $('#page-title').textContent='Notifications';$('#create-toggle').classList.add('hidden');$('#app-content').innerHTML='<div class="loading">Loading notifications...</div>';try{const data=await request('/notifications');state.notifications=data;$('#app-content').innerHTML=data.length?data.map(item=>`<article class="notification ${item.read?'':'unread'}" data-notif="${item.id}" style="cursor:pointer"><div><strong>${esc(notificationTypeLabel(item.type))}</strong><p class="muted">${esc(item.message)}</p><small class="muted">${date(item.createdAt)}</small></div>${item.read?'':'<button class="button secondary" data-read="'+item.id+'">Mark read</button>'}</article>`).join(''):'<div class="empty">No notifications found. Notifications appear here automatically when a match involving you is scheduled, or when a tournament you are part of publishes its final results.</div>';document.querySelectorAll('[data-notif]').forEach(el=>el.onclick=(event)=>{if(event.target.closest('[data-read]'))return;const item=state.notifications.find(n=>String(n.id)===el.dataset.notif);if(item)openNotificationDrawer(item)});document.querySelectorAll('[data-read]').forEach(b=>b.onclick=async(event)=>{event.stopPropagation();await request(`/notifications/${b.dataset.read}/read`,{method:'PUT'});renderNotifications();loadNotifications()})}catch(error){$('#app-content').innerHTML=`<div class="error-box">${esc(error.message)}</div>`}}
document.querySelectorAll('[data-auth]').forEach(tab=>tab.onclick=()=>showAuth(tab.dataset.auth));$('#auth-form').onsubmit=authSubmit;$('#logout').onclick=()=>{stopNotificationPolling();state.credentials=null;state.username=null;state.role=null;showAuth()};$('#create-toggle').onclick=renderCreate;document.querySelectorAll('[data-page]').forEach(item=>item.onclick=()=>{document.querySelectorAll('[data-page]').forEach(n=>n.classList.remove('active'));item.classList.add('active');item.dataset.page==='notifications'?renderNotifications():loadDashboard()});showAuth();

function bracketStatusClass(status){return String(status||'').toLowerCase().replaceAll('_','-')}
function bracketStatusLabel(status){return String(status||'UNKNOWN').replaceAll('_',' ')}
function canManageTournament(){const tournament=state.selected;return Boolean(tournament&&(state.role==='ADMINISTRATOR'||(state.role!=='PARTICIPANT'&&tournament.organizer===state.username)))}
function matchParticipant(match, slot){return slot===1?match.participant1:match.participant2}
function matchScore(match, slot){return slot===1?match.score1:match.score2}
function matchIsBye(match){return !match.participant1Id||!match.participant2Id}
function renderMatchCard(match){const bye=matchIsBye(match);return `<button class="bracket-match ${bye?'is-bye':''}" data-match-id="${match.id}" type="button"><div class="match-card-head"><span>Match ${match.matchNumber}</span><span class="match-state ${bracketStatusClass(match.status)}">${esc(bracketStatusLabel(match.status))}</span></div><div class="match-player ${match.winnerId===match.participant1Id?'is-winner':''}"><span>${esc(match.participant1||'Waiting')}</span><strong>${match.participant1Id?esc(match.score1??'-'):'-'}</strong></div><div class="match-player ${match.winnerId===match.participant2Id?'is-winner':''}"><span>${esc(match.participant2||'Waiting')}</span><strong>${match.participant2Id?esc(match.score2??'-'):'-'}</strong></div><div class="match-card-foot">${bye?'<span class="bye-label">BYE</span>':match.scheduledTime?esc(new Date(match.scheduledTime).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})):'Awaiting schedule'}<span>Open details</span></div></button>`}
function matchDetails(match){const bye=matchIsBye(match);const canResult=canManageTournament()&&match.status==='READY'&&!bye;const scheduled=match.scheduledTime?new Date(match.scheduledTime).toLocaleString():'Not scheduled';return `<div class="drawer-backdrop" data-close-drawer></div><aside class="match-drawer" role="dialog" aria-modal="true" aria-labelledby="match-drawer-title"><button class="drawer-close" type="button" data-close-drawer aria-label="Close match details">&times;</button><p class="eyebrow">Round ${match.round} / Match ${match.matchNumber}</p><h2 id="match-drawer-title">${esc(state.selected.name)}</h2><div class="drawer-status"><span class="match-state ${bracketStatusClass(match.status)}">${esc(bracketStatusLabel(match.status))}</span>${bye?'<span class="bye-label">BYE</span>':''}</div><dl class="match-facts"><div><dt>Scheduled</dt><dd>${esc(scheduled)}</dd></div><div><dt>Round</dt><dd>${match.round}</dd></div></dl><div class="drawer-players"><div class="drawer-player ${match.winnerId===match.participant1Id?'is-winner':''}"><span>${esc(match.participant1||'Waiting for participant')}</span><strong>${match.participant1Id?esc(match.score1??'-'):'-'}</strong>${match.winnerId===match.participant1Id?'<small>Winner</small>':''}</div><div class="drawer-player ${match.winnerId===match.participant2Id?'is-winner':''}"><span>${esc(match.participant2||'Waiting for participant')}</span><strong>${match.participant2Id?esc(match.score2??'-'):'-'}</strong>${match.winnerId===match.participant2Id?'<small>Winner</small>':''}</div></div>${canResult?`<form id="result-form" class="result-form"><h3>Enter result</h3><label>${esc(match.participant1)}<input name="score1" type="number" min="0" step="1" required></label><label>${esc(match.participant2)}<input name="score2" type="number" min="0" step="1" required></label><p class="form-error" id="result-error"></p><button class="button primary wide" type="submit">Submit result</button></form>`:match.status==='READY'&&!bye?'<p class="drawer-note">This match is ready. Only the tournament organizer or an administrator can enter its result.</p>':match.status==='PENDING'?'<p class="drawer-note">This match is waiting for both participants to advance.</p>':''}</aside>`}
function closeMatchDrawer(){document.querySelector('.drawer-backdrop')?.remove();document.querySelector('.match-drawer')?.remove()}
function openMatchDrawer(match){closeMatchDrawer();document.body.insertAdjacentHTML('beforeend',matchDetails(match));document.querySelectorAll('[data-close-drawer]').forEach(node=>node.onclick=closeMatchDrawer);const form=$('#result-form');if(form)form.onsubmit=async event=>{event.preventDefault();const formData=new FormData(form);const score1=Number(formData.get('score1'));const score2=Number(formData.get('score2'));const error=$('#result-error');if(!Number.isInteger(score1)||!Number.isInteger(score2)||score1<0||score2<0||score1===score2){error.textContent='Enter two different non-negative scores.';return}const submit=form.querySelector('button');submit.disabled=true;error.textContent='';try{await request(`/matches/${match.id}/result`,{method:'POST',body:JSON.stringify({score1,score2})});closeMatchDrawer();toast('Result saved and bracket advanced');await renderDetailBody('bracket')}catch(requestError){error.textContent=requestError.message;submit.disabled=false}}}
async function renderDetailBody(tab){const body=$('#detail-body');body.innerHTML='<div class="loading">Loading data...</div>';try{if(tab==='overview'){const data=await request(`/tournaments/${state.selected.id}/participants`);body.innerHTML=`<div class="section-head"><h2>Participants</h2><span class="muted">${data.length} registered</span></div>${data.length?`<table class="data-table"><thead><tr><th>Name</th><th>Status</th><th>Notifications</th></tr></thead><tbody>${data.map(p=>`<tr><td>${esc(p.name)}</td><td><span class="badge">${esc(p.status)}</span></td><td>${p.linkedUsername?`<span class="badge" style="background:var(--mint);color:var(--green)">@${esc(p.linkedUsername)}</span>`:'<span class="muted">Not linked</span>'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No participants registered.</div>'}`}else if(tab==='bracket'){const data=await request(`/tournaments/${state.selected.id}/bracket`);if(!data.length){body.innerHTML='<div class="empty">Bracket has not been generated yet.</div>';return}const rounds=[...new Set(data.map(match=>match.round))].sort((a,b)=>a-b);body.innerHTML=`<div class="bracket-toolbar"><div><p class="eyebrow">Live bracket</p><h2>${esc(state.selected.name)}</h2></div><button class="button secondary" id="refresh-bracket" type="button">Refresh bracket</button></div><div class="bracket-scroll"><div class="bracket">${rounds.map(round=>`<section class="round"><header class="round-header"><span>Round ${round}</span><small>${data.filter(match=>match.round===round).length} matches</small></header><div class="round-matches">${data.filter(match=>match.round===round).map(renderMatchCard).join('')}</div></section>`).join('')}</div></div>`;document.querySelectorAll('[data-match-id]').forEach(button=>button.onclick=()=>openMatchDrawer(data.find(match=>String(match.id)===button.dataset.matchId)));$('#refresh-bracket').onclick=()=>renderDetailBody('bracket')}else{const data=await request(`/tournaments/${state.selected.id}/rankings`);body.innerHTML=data.length?`<table class="data-table"><thead><tr><th>#</th><th>Participant</th><th>Played</th><th>Wins</th><th>Losses</th><th>Score Diff</th><th>Points</th></tr></thead><tbody>${data.map(p=>`<tr><td><strong>${p.placement}</strong></td><td>${esc(p.participant)}</td><td>${p.matchesPlayed}</td><td>${p.wins}</td><td>${p.losses}</td><td>${p.scoreDifference>0?'+':''}${p.scoreDifference}</td><td>${p.points}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Rankings appear after matches are completed.</div>'}}catch(error){body.innerHTML=`<div class="error-box">${esc(error.message)}</div>`}}
const baseRenderDetailBody = renderDetailBody;
renderDetailBody = async (tab) => {
	if (tab === 'overview' && state.selected?.format === 'GROUPS') return renderGroupAssignment();
	return baseRenderDetailBody(tab);
};
async function renderGroupAssignment() {
	const body = $('#detail-body');
	body.innerHTML = '<div class="loading">Loading groups...</div>';
	try {
		const [participants, groups] = await Promise.all([
			request(`/tournaments/${state.selected.id}/participants`),
			request(`/tournaments/${state.selected.id}/groups`)
		]);
		const assigned = new Map(groups.flatMap(group => group.participants.map(participant => [participant.id, group.id])));
		const canEdit = canManageTournament() && state.selected.status === 'REGISTRATION';
		const groupCards = groups.map(group => `<article class="tournament-card"><div class="card-top"><span class="badge">${esc(group.name)}</span><span class="muted">${group.participants.length} assigned</span></div>${group.participants.length ? group.participants.map(participant => `<div class="card-meta"><span>${esc(participant.name)}</span>${canEdit ? `<button class="text-button" data-remove-group="${group.id}" data-remove-participant="${participant.id}">Remove</button>` : ''}</div>`).join('') : '<p class="muted">No participants assigned.</p>'}</article>`).join('');
		const unassigned = participants.filter(participant => !assigned.has(participant.id));
		body.innerHTML = `<div class="section-head"><div><h2>Group assignments</h2><p class="muted">Assign each participant to exactly one group before generating matches.</p></div>${canEdit ? '<form id="create-group-form" class="inline-form"><input name="name" required maxlength="50" placeholder="New group name"><button class="button secondary" type="submit">Create group</button></form>' : ''}</div><div class="tournament-list">${groupCards || '<div class="empty">Create a group to begin.</div>'}</div><article class="tournament-card"><div class="card-top"><span class="badge">Unassigned</span><span class="muted">${unassigned.length} remaining</span></div>${unassigned.length ? unassigned.map(participant => `<div class="card-meta"><span>${esc(participant.name)}</span>${canEdit && groups.length ? `<select data-assign-participant="${participant.id}"><option value="">Assign to...</option>${groups.map(group => `<option value="${group.id}">${esc(group.name)}</option>`).join('')}</select>` : ''}</div>`).join('') : '<p class="muted">Every participant is assigned.</p>'}</article>`;
		if ($('#create-group-form')) $('#create-group-form').onsubmit = async event => { event.preventDefault(); const name = new FormData(event.target).get('name'); try { await request(`/tournaments/${state.selected.id}/groups`, {method:'POST', body:JSON.stringify({name})}); toast('Group created'); renderGroupAssignment(); } catch (error) { toast(error.message); } };
		document.querySelectorAll('[data-assign-participant]').forEach(select => select.onchange = async () => { if (!select.value) return; try { await request(`/tournaments/${state.selected.id}/groups/${select.value}/participants/${select.dataset.assignParticipant}`, {method:'PUT'}); renderGroupAssignment(); } catch (error) { toast(error.message); } });
		document.querySelectorAll('[data-remove-group]').forEach(button => button.onclick = async () => { try { await request(`/tournaments/${state.selected.id}/groups/${button.dataset.removeGroup}/participants/${button.dataset.removeParticipant}`, {method:'DELETE'}); renderGroupAssignment(); } catch (error) { toast(error.message); } });
	} catch (error) { body.innerHTML = `<div class="error-box">${esc(error.message)}</div>`; }
}
